import type { Metadata } from "next";
import {
  Anton,
  Geist,
  Geist_Mono,
  Poppins,
  UnifrakturCook,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar/navbar";
import { Footer } from "@/components/shared/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Movie World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}antialiased bg-black min-h-screen text-white`}
      >
        {/* navbar start */}

        <Navbar />

        {children}

        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
